### PR TITLE
Updated languages.

### PR DESCRIPTION
**Pull request by ldsiosdev**

### CODE REVIEW

**Comment by hiltonc** [comment]
@jrwagz Not sure where ", BofMSel" came from, was that added to the spreadsheet?

**Comment by jrwagz** [comment]
I don't recognize the change.  Maybe @samuelbradshaw  does?

**Comment by samuelbradshaw** [comment]
Oops, I added that row – I can remove it. I was marking which languages' scriptures have complete translations, which ones have a triple, just a Book of Mormon, or just Selections from the Book of Mormon. I didn't think about the export. :)

**Comment by samuelbradshaw** [comment]
Just deleted the row, so it should be good.

**Comment by samuelbradshaw** [comment]
Just deleted the row, so it should be good.

**Pull request closed without merging**
